### ISSUE TITLE
RuntimeError: cannot join thread before it is

### ISSUE THREAD

**Issue by arbrog** [aka-katto/dandere2x#109]
Version: 1.7.1 
Windows 10 
Error on second run of dandere2x. Deleting folder in workspace/defaul seems to fix it
```workspace = ..\workspace\default\
log file is: H:\Temp Testing\release\workspace\log_folder\dandere2x1583207393.9632955.log
is not resume session
threading at start of runtime
[<_MainThread(MainThread, started 20768)>, <Dandere2x(dandere2x_thread, started 16684)>]
creating of H:\Temp Testing\release\workspace\default\ failed
Creation of the directory H:\Temp Testing\release\workspace\default\compressed_moving\ failed
Creation of the directory H:\Temp Testing\release\workspace\default\encoded\ failed
Creation of the directory H:\Temp Testing\release\workspace\default\residual_upscaled\ failed
Creation of the directory H:\Temp Testing\release\workspace\default\debug\ failed
Creation of the directory H:\Temp Testing\release\workspace\default\compressed_static\ failed
Creation of the directory H:\Temp Testing\release\workspace\default\pframe_data\ failed
Creation of the directory H:\Temp Testing\release\workspace\default\fade_data\ failed
Traceback (Creation of the directory H:\Temp Testing\release\workspace\default\residual_data\ failed
most reCreation of the directory H:\Temp Testing\release\workspace\default\merged\ failed
cent call last):
  File "gui_driveCreation of the directory H:\Temp Testing\release\workspace\default\correction_data\ failed
r.py", Creation of the directory H:\Temp Testing\release\workspace\default\temp_image_folder\ failed
liCreation of the directory H:\Temp Testing\release\workspace\default\inputs\ failed
ne 3Creation of the directory H:\Temp Testing\release\workspace\default\console_output\ failed
2, inCreation of the directory H:\Temp Testing\release\workspace\default\residual_images\ failed
 rForcing Resizing to match blocksize..
un
  FNew width -> 1920
ile "gui_driver.py", line 38, in join
  File "dandere2x.py", line 129, in join
  File "dandNew height -> 860
ere2xlib\core\residual.py", line 42, in join
  File "threading.py", line 1039, in join
RuntimeError: cannot join thread before it is started```

**Comment by aka-katto** [comment]
Give 1.8 a try, I think I fixed this bug

**Comment by arbrog** [comment]
hmmm run 1.8 still happened to me.
Steps to reproduce:
1) open gui
2) upscale vid
3) after completion upscale another
Log just showed stuff from 1st successful upscale
[dandere2x1583266362.3741627.log](https://github.com/aka-katto/dandere2x/files/4283410/dandere2x1583266362.3741627.log)
[console output.txt](https://github.com/aka-katto/dandere2x/files/4283412/console.output.txt)

**Comment by aka-katto** [comment]
> Trying to delete workspace via RM tree threw PermissionError - Dandere2x may not work.

I would guess that windows is lacking permissions to delete the workspace folder for some reason, can you confirm that you're running d2x as adminstrator?

If not, manually deleting ```H:\Temp Testing\1.8_release\workspace\default\``` 

should fix the issue.

**Comment by arbrog** [comment]
Same result running as admin. I have a workaround so it's fine.
